### ISSUE TITLE
'Kotlin Slack channel: get invite here' link not working

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/kotlin#120]
Hi all,

I was just browsing the Kotlin track and while reading around about the language I noticed that if you try and [get an invite](http://exercism.io/languages/kotlin/resources) to the Kotlin Slack channel, it takes you to an empty [Heroku page](http://kotlinslackin.herokuapp.com/).

**Comment by stkent** [comment]
Thanks for reporting! I just fixed this in master, so it should be fixed the next time the website is deployed. I'll leave the issue open until that happens to make sure I verify it.

**Comment by stkent** [comment]
Can confirm, is now live on the website! Closing this issue :)
