### ISSUE TITLE
HandshakeCalculatorTest passes all tests in IDEA even when the implementation is just TODO()

### ISSUE THREAD

**Issue by GrahamLea** [exercism/kotlin#128]
Individual tests fail, but running the whole test class always passes.
I don't know enough about Gradle to help you by tracking down the cause, sorry.

**Comment by mikegehard** [comment]
@GrahamLea Thanks for the report. Do you happen to know if this is still an issue?

**Comment by GrahamLea** [comment]
I’m not sure, sorry. This was a long time ago.  

--
Graham Lea
graham@grahamlea.com

**Comment by mikegehard** [comment]
No worries. Thanks for taking the time to respond. I'm going to close this and if it is still an issue folks will hopefully report it again. :-)
