### ISSUE TITLE
Document the need to remove the `@Ignore` from other tests in each exercise

### ISSUE THREAD

**Issue by duckpuppy** [exercism/kotlin#130]
In #30, each test after the first was `@Ignore`d with the idea that the student would remove that annotation from the remaining tests.  In https://github.com/exercism/kotlin/pull/30#issuecomment-277893270, it was mentioned that a future PR was inbound to address documenting that.  I began the Kotlin track yesterday (5/17/2018) and nowhere in the `TUTORIAL.md` or `README.md` for hello-world was there a mention of removing them.  I didn't even notice skipped tests until the second lesson, and only because I'm a seasoned developer familiar with testing frameworks did I think to investigate the test file and remove them.

**Comment by katrinleinweber** [comment]
@jtigger did that in https://github.com/exercism/kotlin/pull/31, but it's indeed not longer there.

**Comment by mikegehard** [comment]
@duckpuppy Do you know if this is still an issue?

**Comment by blueglyph** [comment]
> @duckpuppy Do you know if this is still an issue?

Hello, this is still an issue as reported in #300, #301 (and other tests)

**Comment by mikegehard** [comment]
Thanks @blueglyph. 

I'll take a look at the commits referenced above and back in some language around the @Ignore annotations.

**Comment by mikegehard** [comment]
I believe this is at least partially addressed by #296 so I'm closing.

If there is more work to be done, please file another issue or open a pull request with specifics.

Thanks!
