### ISSUE TITLE
Unable import project on IntelliJ

### ISSUE THREAD

**Issue by castrors** [exercism/kotlin#131]
I'm having trouble to import an projetct to IntelliJ. I got that message: 
*Please, use JDK instead of JRE for Gradle importer.*

IntelliJ version 2017.3.5

**Comment by sjwarner-bp** [comment]
Hi @castrors! I'm not a maintainer for Kotlin, but have you tried [this help page](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206825155-gradle-project-import-resolve-error). It looks like the same error you've had, and seems to explain it pretty nicely :slightly_smiling_face: 

It's probably also worth knowing the difference between the JDK and the JRE if you don't already - [here is a great StackOverflow answer](https://stackoverflow.com/questions/1906445/what-is-the-difference-between-jdk-and-jre) explaining the differences :slightly_smiling_face:
