### ISSUE TITLE
acronym: update tests and version file (v1.1.0 -> v1.3.0)

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/kotlin#141]
Please update the version specified in the acronym version file from 1.1.0 to 1.3.0.

This update has been caused by the application of a new input policy, renaming of a test case, and removal of a redundant test case.

Please additionally update the test suite to match the [canonical-data](https://github.com/exercism/problem-specifications/commits/master/exercises/acronym/canonical-data.json). `fromAllCapsWord()` test should be removed.

**Comment by beatbrot** [comment]
I'll handle it!

**Comment by beatbrot** [comment]
See #249

**Comment by sjwarner-bp** [comment]
Closed via #249
