### ISSUE TITLE
phone-number: update tests and version file (v1.2.0 -> v1.4.0)

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/kotlin#161]
Please update the version specified in the phone-number version file from 1.2.0 to 1.4.0.

This update has been caused by the application of a new input policy, and a change of the test suite.

Please additionally update the test suite to match the [canonical-data](https://github.com/exercism/problem-specifications/commits/master/exercises/phone-number/canonical-data.json).

**Comment by beatbrot** [comment]
I'll take care!

**Comment by beatbrot** [comment]
See #255

**Comment by sjwarner-bp** [comment]
Closed via #255 - Thanks @beatbrot
