### ISSUE TITLE
bob: update tests and version file (v1.0.0 -> v1.2.0)

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/kotlin#167]
Please update the version specified in the bob version file from 1.0.0 to 1.2.0.

This update has been caused by the application of a new input policy, and a new rule being added to Bob's behaviour (resulting in test suite changes).

Please update the [test suite](https://github.com/exercism/kotlin/blob/master/exercises/bob/src/test/kotlin/BobTest.kt) to match the [canonical data](https://github.com/exercism/problem-specifications/commits/master/exercises/bob/canonical-data.json). The [reference solution](https://github.com/exercism/kotlin/blob/master/exercises/bob/.meta/src/reference/kotlin/Bob.kt) will also require an update to pass the new test suite.

This pairs with issue #127.

**Comment by mdowds** [comment]
I'll take a look at this one.
