### ISSUE TITLE
grade-school: update test suite and version file to 1.0.0

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/kotlin#174]
Please add a version file `exercises/grade-school/.meta/version` with the string 1.0.0 for the series exercise.

Since implementing this exercise, [canonical-data](https://github.com/exercism/problem-specifications/commits/master/exercises/grade-school/canonical-data.json) has been added for series in the problem-specifications repo. In order ensure our tests cover all cases and are consistent with other tracks, we should try to mirror problem-specifications as closely as possible.

Because of this, the [test suite](https://github.com/exercism/kotlin/blob/master/exercises/grade-school/src/test/kotlin/SchoolTest.kt) should be rewritten to comply with version 1.0.0.

Additionally, the [reference implementation](https://github.com/exercism/kotlin/blob/master/exercises/grade-school/.meta/src/reference/kotlin/School.kt) will need updating to pass the new test suite.

**Comment by sup95** [comment]
I'd like to work on this. :)

**Comment by eparovyshnaya** [comment]
[done](https://tracks.exercism.io/kotlin/master/versions) by [PR 390](https://github.com/exercism/kotlin/pull/390)
