### ISSUE TITLE
robot-simulator: update tests and version file (v2.0.0 -> v2.2.0)

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/kotlin#175]
Please update the version specified in the robot-simulator version file from 2.0.0 to 2.2.0.

This update has been caused by the application of a new input policy and a change in the set of inputs.

If necessary, please additionally update the test suite to match the [canonical-data](https://github.com/exercism/problem-specifications/commits/master/exercises/robot-simulator/canonical-data.json).

**Comment by sup95** [comment]
I'll work on this!
