### ISSUE TITLE
anagram: update tests and version file (v1.0.1 -> v1.2.0)

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/kotlin#180]
Please update the version specified in the anagram version file from 1.0.1 to 1.2.0.

This update has been caused by the application of a new input policy, and the removal of several duplicate test cases.

Please additionally update the test suite to match the [canonical-data](https://github.com/exercism/problem-specifications/commits/master/exercises/anagram/canonical-data.json).

**Comment by sup95** [comment]
I'll take this up! :)
