### ISSUE TITLE
clock: update tests and version file (v1.0.1 -> v2.2.1)

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/kotlin#183]
Please update the version specified in the clock version file from 1.0.1 to 2.2.1.

This update has been caused by the application of a new input policy, comment edits, and a change to the structure of tests. The largest part of this is that now, instead of adding a negative number of minutes, a set of subtraction tests should exist.

Please update the test suite to match the [canonical-data](https://github.com/exercism/problem-specifications/commits/master/exercises/clock/canonical-data.json), and ensure that the reference solution passes these tests.

**Comment by lihofm** [comment]
Will take care of it!
