### ISSUE TITLE
simple-cipher: update test suite and version file to 1.0.0

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/kotlin#184]
Please add a version file `exercises/simple-cipher/.meta/version` with the string 1.0.0 for the series exercise.

Since implementing this exercise, [canonical-data](https://github.com/exercism/problem-specifications/commits/master/exercises/simple-cipher/canonical-data.json) has been added for series in the problem-specifications repo. In order ensure our tests cover all cases and are consistent with other tracks, we should try to mirror problem-specifications as closely as possible.

Because of this, the [test suite](https://github.com/exercism/kotlin/blob/master/exercises/simple-cipher/src/test/kotlin) should be rewritten to comply with version 1.0.0.

Additionally, the [reference implementation](https://github.com/exercism/kotlin/blob/master/exercises/simple-cipher/.meta/src/reference/kotlin) will need updating to pass the new test suite.

**Comment by mdowds** [comment]
I'll take a look at this

**Comment by mikegehard** [comment]
The commit above fails the unit tests.
