### ISSUE TITLE
complex-numbers: update tests and version file (v1.0.0 -> v1.3.0)

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/kotlin#185]
Please update the version specified in the complex-numbers version file from 1.0.0 to 1.3.0.

This update has been caused by the application of a new input policy, and the addition of a new test case.

Please additionally update the test suite to match the [canonical-data](https://github.com/exercism/problem-specifications/commits/master/exercises/complex-numbers/canonical-data.json). The test described by "Exponential of a number with real and imaginary part" should be added, and the reference solution updated if necessary.

**Comment by DanCorder** [comment]
I can take a look at this
