### ISSUE TITLE
forth: update tests and version file (v1.3.0 -> v1.6.0)

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/kotlin#187]
Please update the version specified in the forth version file from 1.3.0 to 1.6.0.

This update has been caused by the application of a new input policy, and the addition of several new test cases.

Please additionally update the test suite to match the [canonical-data](https://github.com/exercism/problem-specifications/commits/master/exercises/forth/canonical-data.json), and update the reference solution to pass all new tests if needed.

**Comment by luoken** [comment]
This issue is done [here](https://github.com/exercism/kotlin/pull/263).

**Comment by sjwarner-bp** [comment]
Closed via #263 - Thanks @luoken
