### ISSUE TITLE
Fix getting started instructions for kotlin

### ISSUE THREAD

**Issue by jackhughesweb** [exercism/kotlin#238]
Some exercise README templates contain links to pages which no longer exist in v2 Exercism.

For example, C++'s README template had a link to /languages/cpp for instructions on running tests. The correct URLs to use can be found in the 'Still stuck?' sidebar of exercise pages on the live site. You'll need to join the track and go to the first exercise to see them.

Please update any broken links in the 'config/exercise_readme.go.tmpl' file, and run 'configlet generate .' to generate new exercise READMEs with the fixes.

Instructions for generating READMEs with configlet can be found at:
https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md#generating-a-readme

Instructions for installing configlet can be found at:
https://github.com/exercism/docs/blob/bc29a1884da6c401de6f3f211d03aabe53894318/language-tracks/launch/first-exercise.md#the-configlet-tool

Tracking exercism/exercism.io#4102

**Comment by mikegehard** [comment]
@jackhughesweb I don't see any links in https://github.com/exercism/kotlin/blob/master/config/exercise_readme.go.tmpl. I'm new to maintaining a track so does this mean there is no work here?

**Comment by jackhughesweb** [comment]
@mikegehard Thank you for taking a look into this 😄

I've quickly searched the repo for links to the Exercism website, and have found three (of the same) links that are currently broken in `docs/TESTS.md`: they each point to `http://exercism.io/languages/kotlin/help`, which redirects to Exercism's own FAQ instead of the help page for Kotlin. 

I'm not sure what URL to replace this with, other than the pages linked at the bottom of the [installation page](https://exercism.io/tracks/kotlin/installation), under the heading `More Kotlin resources`?

**Comment by mikegehard** [comment]
Thanks for the response!

That's a great question...not sure where that should point. I'll give it some thought.
