### ISSUE TITLE
Tagging issues with hacktoberfest to get more help?

### ISSUE THREAD

**Issue by beatbrot** [exercism/kotlin#254]
Hey :) 

Did you ever consider tagging issues with [hacktoberfest](https://hacktoberfest.digitalocean.com/) so that we could get more help? 
[exercism/java](https://github.com/exercism/java/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest) does the same with great success!

**Comment by mikegehard** [comment]
Thanks for the idea @beatbrot. We'll try that next year for sure.
