### ISSUE TITLE
list-ops: it's not clear what existing functions/operators you can use

### ISSUE THREAD

**Issue by myronmarston** [exercism/kotlin#280]
The current instructions for the list-ops say:

> In functional languages list operations like length, map, and reduce are very common. Implement a series of basic list operations, without using existing functions.

AFAIK, Kotlin does not provide a way to do anything with a list without using functions.  Even built in operators like `[]` wind up calling functions (e.g. `get`).  So I don't get how it's possible to do this exercise without using at least some of the built in Kotlin or Java functions.

I've looked over [most of the community solutions](https://exercism.io/tracks/kotlin/exercises/list-ops/solutions) and all the ones I've looked at use some existing functions like `drop`, `+`, `isEmpty`, etc.

Can the instructions get clarified to be more specific about what functions you are allowed to use?

**Comment by mikegehard** [comment]
@myronmarston Did the answer from @blogscot help any?

If not, let me know.
If so, any chance you can submit a PR to https://github.com/exercism/kotlin/blob/master/exercises/list-ops/README.md that would make that more clear going forwards?

**Comment by myronmarston** [comment]
Yes, it did help.  I opened #285 to clarify it.

FWIW, I think other people would probably not be as confused as I was about this. I had previously done the corresponding list-ops exercise for the elixir track, which goes out of its way to say:

```
  # Please don't use any external modules (especially List) in your
  # implementation. The point of this exercise is to create these basic functions
  # yourself.
  #
  # Note that `++` is a function from an external module (Kernel, which is
  # automatically imported) and so shouldn't be used either.
```

Elixir's built-in pattern matching and recursion allow you to solve the list-ops exercise without using any function calls whatsover, so that's what I walked into the kotlin track thinking about.  Most people won't have that in their minds when working through the kotlin track :).
