### ISSUE TITLE
docs: `exercism fetch` out of date

### ISSUE THREAD

**Issue by petertseng** [exercism/kotlin#283]
https://github.com/exercism/kotlin/blob/master/docs/TESTS.md and https://github.com/exercism/kotlin/blob/master/exercises/hello-world/TUTORIAL.md have `exercism fetch`. now it should probably be changed to just direct the student to the `exercism download` command that appears on the exercise page. If it is necessary to give a specific example, perhaps the one for hello world? `exercism download --exercise=hello-world --track=kotlin` or two-fer `exercism download --exercise=two-fer --track=kotlin`

**Comment by mikegehard** [comment]
Thanks for the issue @petertseng!

Would you have time to review some changes to confirm this solves the issue?
Please see https://github.com/exercism/kotlin/pull/284
