### ISSUE TITLE
Add resistor exercises

### ISSUE THREAD

**Issue by mikegehard** [exercism/kotlin#289]
[Problem specification](https://github.com/exercism/problem-specifications/tree/master/exercises/resistor-color)

~~https://exercism-team.slack.com/archives/GC3K95MRR/p1552128336013100~~

**Comment by dector** [comment]
Unfortunately link to Slack is broken. :(

[Problem specification](https://github.com/exercism/problem-specifications/tree/master/exercises/resistor-color).

**Comment by eparovyshnaya** [comment]
All *resistor-color* exercises are added by @lathspell:
   - [resistor-color](https://github.com/exercism/kotlin/pull/402)
   - [resistor-color-duo](https://github.com/exercism/kotlin/pull/403)
   - [resistor-color-trio](https://github.com/exercism/kotlin/pull/405)
