### ISSUE TITLE
Update simple-cipher to latest version of the cannonical data

### ISSUE THREAD

**Issue by mikegehard** [exercism/kotlin#291]
https://github.com/exercism/problem-specifications/blob/master/exercises/simple-cipher/canonical-data.json

There was an initial attempt to update to 1.1.0 that I couldn't get to pass locally. If you want to start with that commit (https://github.com/exercism/kotlin/commit/d706824d7ef617aaa199bc53e026927e09d1cc42), revert it and then update to 2.0.0, that would be a good way to start.

**Comment by eparovyshnaya** [comment]
Closed by #409
