### ISSUE TITLE
Error in test for Two Fer exercise

### ISSUE THREAD

**Issue by antimoroma** [exercism/kotlin#293]
File :
exercises/two-fer/src/test/kotlin/TwoferTest.kt
Actual test is 
    @Test
    @Ignore
    fun emptyStringGiven() {
        assertEquals("One for , one for me.", twofer(""))
    }
Must be 
 assertEquals("One for you, one for me.", twofer(""))

**Comment by gpunto** [comment]
I think the empty string is still considered a name, while "no name" is only when no string is given at all, like in:
`@Test
fun noNameGiven() {
    assertEquals("One for you, one for me.", twofer())
}`

**Comment by antimoroma** [comment]
May be the requirement still have to be more precisely, viceversa we start to talk about opinion and not requierments. 
For example
What is a name? 
In which domain we consider a name valid if it's empty?
What is the domain of the problem?

May be specifyng the domain of the problem more clearly  (and what is a name in this domain)  could make things more clear, so it's possible to differentiate from an empty name and a "no name given".

For example (talking only about the name): 
A name is a simple string (casually in the specification and in the example we use "Bob", "me" , "you" but this is miss leading a name didn't not indicate a Person (name) or similar thing is a simple String, a sequence of character or a sequence of no character (empty String)).
This (quite strange) specification could leave less space to miss leading interpretation so we are sure that '' is a name.

Another definition could be : a name is a "Person name" or a Pronouns. This give us that a name could not be an "empty" string like '' or a "null" string. (less strange in my opinion, and quite a classic point of view for a "name")
Just my .00002 cent

**Comment by SleeplessByte** [comment]
Not all people have a name, so an empty string should be a valid name and not be replaced with `you`. 

In Kotlin there are many many better ways to indicate NoNameGiven (vs empty name), for example a sealed data type with two options:
- `NoNameGiven`
- `NameGiven(val name: string)`

Which would completely resolve the issue with checking for an empty string.

That said, `null` is a _better_ candidate for explicit no name here.

**Comment by antimoroma** [comment]
If this is the case:
Not all people have a name, so an empty string should be a valid name and not be replaced with you

Better to specify in problem requirement, is simple o no to add this simple specification?

And this is a problem specification not related to language implementation (different domain)

That said is better to avoid null in program...(https://medium.com/@hinchman_amanda/null-pointer-references-the-billion-dollar-mistake-1e616534d485)

**Comment by SleeplessByte** [comment]
I don't feel like you've read my response properly. I never said `null` *should* be used, but using it to indicate the lack of a name here is _better_ than to assume `''` is no name.

> Better to specify in problem requirement, is simple o no to add this simple specification?

Yes, this can be added to an `/exercices/<exercise>/.../hints.md`! I you'd like, you could open a PR :heart:.

However, don't forget that the tests are part of the instructions. If you follow TDD, there should be no issue understanding that at least in the Kotlin track, `''` is to be interpreted as an actual name, without any content.

**Comment by antimoroma** [comment]
Sorry if i didn't understand your suggestion my fault.

About TDD i know "something" and use it "sometime" about this, but again this is not a programming problem but a domain/problem description problem in my point of view.

Before open a PR it's better to feel sure that i understand everything, it seems that every suggestion in this project is "quite" complex , i don't sense  a constructive approach,  but an "imperative" approach (may be my fault again) so i prefer stopping my suggestion here

**Comment by SleeplessByte** [comment]
> About TDD i know "something" and use it "sometime" about this, but again this is not a programming problem but a domain/problem description problem in my point of view.

In that case have a look at the `problem-specifications` repository!

**Comment by mikegehard** [comment]
@antimoroma Sounds like your and @SleeplessByte have come to an understanding?

If so, please close this issue so we know it has been handled.
If you still have questions/concerns, please let me know.
