### ISSUE TITLE
Errors in: Leap

### ISSUE THREAD

**Issue by blueglyph** [exercism/kotlin#301]
Common problems also found in other tests.

1) Problem description too vague: _Given a year, report if it is a leap year._
- function/class?
- name?
- file name?
- return type?
- restrictions?

=> the user has to guess what to do, from the test suite.

2) Test suite is incomplete, most tests are skipped because of `@Ignored` tags.

=> test unreliable

```kotlin
class LeapTest {

    @Test
    fun yearNotDivisibleBy4() {
        assertFalse(Year(2015).isLeap)
    }

    @Ignore
    @Test
    fun yearDivisibleBy4NotDivisibleBy100() {
        assertTrue(Year(1996).isLeap)
    }

    @Ignore
    @Test
    fun yearDivisibleBy100NotDivisibleBy400() {
        assertFalse(Year(2100).isLeap)
    }

    @Ignore
    @Test
    fun yearDivisibleBy400() {
        assertTrue(Year(2000).isLeap)
    }

}

```

**Comment by blueglyph** [comment]
As a solution for 1), suggestion:

Given a year, report if it is a leap year.
Define a class Year, 
- taking an integer for the year as constructor parameter,
- providing a isLeap boolean property which is true when the year is a leap year
- years are given with 4 digits, e.g. 2019 (and not only 19 by skipping the century digits).

**Comment by blueglyph** [comment]
As a solution for 2), obviously:

```kotlin
import org.junit.Test
import org.junit.Ignore
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class LeapTest {

    @Test
    fun yearNotDivisibleBy4() {
        assertFalse(Year(2015).isLeap)
    }

    @Test
    fun yearDivisibleBy4NotDivisibleBy100() {
        assertTrue(Year(1996).isLeap)
    }

    @Test
    fun yearDivisibleBy100NotDivisibleBy400() {
        assertFalse(Year(2100).isLeap)
    }

    @Test
    fun yearDivisibleBy400() {
        assertTrue(Year(2000).isLeap)
    }
}
```

**Comment by mikegehard** [comment]
Thanks for the report. #2 should be addressed in #296. Each assignment description will let folks know to remove the @Ignore. Hopefully that helps once it is deployed to prod. If it doesn't, please let me know.

**Comment by mikegehard** [comment]
In regards to #1, yes it is assumed that the user would use the test suite to answer those questions.

There was a big discussion in this thread (https://github.com/exercism/exercism/issues/856) about the philosophy. Hopefully this helps explain a bit about the dependence on the tests.

**Comment by mikegehard** [comment]
I'm closing this issue for now. If the two discussions above don't solve this for you, please start a discussion here and we can try to find a solution together.

**Comment by blueglyph** [comment]
I see the problem is larger than this specific test. I just given my thoughts from experience in the problem referenced above (#856). Personally, I know how to proceed now so my own problem is solved already, but one may consider the chance that everyone starting the tests will hit the same wall...

**Comment by mikegehard** [comment]
Thanks for taking the time to add your thoughts to #865...I'll track that one to see where Exercism as a whole ends up.
