### ISSUE TITLE
Errors in: Forth

### ISSUE THREAD

**Issue by blueglyph** [exercism/kotlin#302]
The problem description is missing on the webpage (there is only the word 'Introduction').

When trying to download the problem, the following error occurs:

```
exercism download --exercise=forth --track=kotlin
Error: unable to parse API response - invalid character '<' looking for beginning of value
```

(I didn't have problems downloading the other tests)

OS: Win7 Pro x64

**Comment by mikegehard** [comment]
Thanks for the report. 

I'm not sure why that even shows up on the site as it isn't in the config for the exercises:
https://github.com/exercism/kotlin/blob/master/config.json

nor is it in the exercises directory:
https://github.com/exercism/kotlin/tree/master/exercises

I've merged in some changes recently and see if those fix it. I'll continue to monitor.

**Comment by blueglyph** [comment]
I've seen it in the branch kytrinyx/inline-insert, perhaps there was a good reason why it was removed.

Would you like me to have a look and test if that works? This seems to be quite an interesting test.

**Comment by blueglyph** [comment]
I tried and solved it, it's indeed very interesting. I would probably add a couple of tests with corner cases (like a definition within a definition, empty definition ": ;" or strings that begin / end with spaces or are empty), but it's already very complete.

**Comment by mikegehard** [comment]
Thanks for taking the time to figure this out. Is there a pull request that. I can take a look at?

**Comment by blueglyph** [comment]
Maybe not, I added those few tests and they were all running fine on my solution, but I realize the reference version breaks with them, and I see no easy fix. It's an unnecessary addition anyway.

Taken as-is from the existing branch should be perfect.

**Comment by Ric0chet-GitHub** [comment]
As of June 28th, this is still broken.  The situation described by blueglyph is still occurring.  It is not possible to start the "Forth" exercise.

> The problem description is missing on the webpage (there is only the word 'Introduction').
> 
> When trying to download the problem, the following error occurs:
> 
 ```
 exercism download --exercise=forth --track=kotlin
 Error: unable to parse API response - invalid character '<' looking for beginning of value
 ```

**Comment by mikegehard** [comment]
Thanks for the report @Ric0chet-GitHub.

I haven't had any time to take a look due to other things going on. Not sure when I get to taking a look...sorry.

**Comment by Ric0chet-GitHub** [comment]
Gotcha.  I realize there are only two Kotlin maintainers.  (It's frustrating as this is the only exercise I haven't completed in that track.)
  
Some more data:  the last person to publish a solution to Forth did it on April 19th.  If that helps to narrow things.  I also should've mentioned that I'm seeing this in Independent mode.

Here's a screen cap:
![Kotlin--Forth](https://user-images.githubusercontent.com/52333533/60371805-5def8d00-99c8-11e9-92ea-2320ba735fa3.png)

**Comment by mikegehard** [comment]
Thanks for the additional info!

**Comment by blueglyph** [comment]
I'm not sure whether it was fixed at some point or not, but the situation as of today is still similar to what I initially reported.

```
> exercism download --exercise=forth --track=kotlin
> Error: unable to parse API response - invalid character '<' looking for beginning of value
```

**Comment by blueglyph** [comment]
For information, I could do an 'exercism submit' by using the correct id in .exercism/metadata.json:

```
{"track":"kotlin","exercise":"acronym","id":"<id>","url":"https://exercism.io/my/solutions/<id>","handle":"<login>","is_requester":true,"auto_approve":false}
```

where `<login>` is my login, and `<id>` the one I see when opening this exercise (and that I don't want to paste here), so `https://exercism.io/my/solutions/<id>`

```
>exercism submit src\main\kotlin\ForthEvaluator.kt


    Your solution has been submitted successfully.
    View it at:


    https://exercism.io/my/solutions/<id>


```

After that I see the exercise as completed, and the correct code correctly uploaded.

**Comment by dector** [comment]
Related to: #312

**Comment by eparovyshnaya** [comment]
Related also to #360

**Comment by eparovyshnaya** [comment]
Closed by [PR 407](https://github.com/exercism/kotlin/pull/407)
