### ISSUE TITLE
gradle or gradlew?

### ISSUE THREAD

**Issue by pramodbharti** [exercism/kotlin#307]
Hi, 
```$ gradlew test``` command is not working for me. 
It returns ```gradlew: command not found```. Any help?

Currently I am using ```$ gradle test``` instead of ```$ gradlew test```.

Thanks

**Comment by blueglyph** [comment]
What's your OS? What steps are you following? It's hard to guess from a basic description like that.

`gradlew` is a shell script, so it should work for anything based on Linux (or Cygwin/Msys, but you have to setup the script for that first). Does it have the execute flag set? Personally I prefer to launch it as argument for the bash shell (sh gradlew).
There's also gradlew.bat for Windows.

In either case, do you run the script from that directory?

I'm just using IntelliJ, it sets up the project correctly from the gradle script.

**Comment by stkent** [comment]
Try `./gradlew test`.

Also note that the `reverse-string` exercise is currently missing some related files. Until that is fixed (by #315) you will indeed need to run the tests for that exercise using a system-wide Gradle installation via `gradle test`.

**Comment by mikegehard** [comment]
@pramodbharti Is this still an issue for you?

If not, please close the issue. We are trying to clean up the "backlog" and this would help us do that.

**Comment by dector** [comment]
@pramodbharti Closing this issue for now.

Feel free to reopen it you still experiencing it!
