### ISSUE TITLE
Unable to locate package ... 

### ISSUE THREAD

**Issue by Kmotrus** [exercism/kotlin#308]
![xxxxxa](https://user-images.githubusercontent.com/52864139/61174741-bae06b00-a5a4-11e9-869d-15bdcd55ecc3.png)

Please can i get help ? what should i do to make it work ?

**Comment by mikegehard** [comment]
Please take a look at the [installation instructions](https://exercism.io/tracks/kotlin/installation) to see if that helps. We have changed to JDK 11 as the base.

Please let me know how this goes or close the issue if everything goes well.

**Comment by dector** [comment]
Hi, @Kmotrus . Do you still experiencing some issues with environment setup?

**Comment by dector** [comment]
@Kmotrus closing this for now. Feel free to ask questions/reopen this issue if you need help with it.
