### ISSUE TITLE
Reintroduce `forth`

### ISSUE THREAD

**Issue by NobbZ** [exercism/kotlin#312]
Since Forth has already been picked up by some students, the deletion of it in a8783b763fe95556bd300ddd4e6bc8a4f4e0350c now causes issues like exercism/exercism#5044.

Please re-introduce the exercise and follow the usual deprecation process or speed up the test suite such removal won't becomes necessary anymore.

**Comment by eparovyshnaya** [comment]
Done by [PR 407](https://github.com/exercism/kotlin/pull/407)
