### ISSUE TITLE
Missing src files 

### ISSUE THREAD

**Issue by spmasterman** [exercism/kotlin#322]
All the src/main/kotlin folders are empty except for a .keep file? Am I missing something?

**Comment by mikegehard** [comment]
Hey there @spmasterman.

The proposed solutions can be found in `/exercises/<exerciseName>/.meta/src/reference/kotlin/` directory.

The `src/main/kotlin` directories are the ones that are sent down when you pull an exercise.

Curious about what you were trying to figure out when you saw that?

**Comment by dector** [comment]
I guess that question wasn't about solutions, but about source files for some exercises. They are missing sometimes indeed

**Comment by mikegehard** [comment]
Gotcha...do you have an example that I can take a look at?

**Comment by dector** [comment]
Sure. :) For example, [here](https://github.com/exercism/kotlin/tree/master/exercises/reverse-string/src/main/kotlin).

**Comment by mikegehard** [comment]
Gotcha...now I'm getting what you are talking about.

So you are expecting the files to be there. Are they there in other languages? Are they there in other Kotlin exercises?

My understanding is that you are to create them as part of your solution. I think I remember some talk about adding them for tracks but not sure where that ended up.

**Comment by dector** [comment]
@mikegehard 

I guess there should be some template file with defined function that don't do anything (or has `TODO()` body in case of Kotlin). For example `reverse-string` exercise should have something like [this](https://github.com/exercism/kotlin/pull/326/files#diff-c87750fb1c6a47e187b3ed2f80939a44R1).

> Are they there in other languages? Are they there in other Kotlin exercises?
Yup, exactly. "Template" files are present for other languages and missed for some exercises in Kotlin track. :)

_BTW Is there a way to become a track maintainer? My motivation is that I'm thinking about giving an advice for students to use exercism as an exercising platform for Kotlin language. But track seems a bit abandoned, to be honest. I can spend some time daily to update all exercises according to [this report](https://tracks.exercism.io/kotlin/master/), improve/update tooling etc. But there are many PRs that are unanswered for few months - so doing it in "usual way" may take quite a while. I can offer my help for maintaining this track. :)_

**Comment by mikegehard** [comment]
Gotcha...so yes it does look like there are a couple of exercises that have files already present in the `src/main/kotlin` directory, like the `react` exercise.

Thanks for sharing that link to the "report". I have never seen that before. :-) 

So yes it looks like the pattern is to add in stub files like this one:
https://raw.githubusercontent.com/exercism/dart/master/exercises/hello-world/lib/hello_world.dart

And yes I do think your comment about this track being under maintained is correct. I've been trying to keep up but life has been getting a lot of my time these days. Having someone step up and help maintain would be great.

Maybe poke around in [this document](https://github.com/exercism/docs/blob/03adceb68dc1c3b06c9158ac179a186b16270428/maintaining-a-track/README.md) to see if there is an easy way to get involved. I've already forgotten how I got added...I think I may have asked in the Slack channel.

It would be great to get someone with more regular time to help and sounds like you have that time.

Let me know how I can help keep that ball rolling.

**Comment by dector** [comment]
> I've been trying to keep up but life has been getting a lot of my time these days.

It's totally okay. Happens to everybody. :smiley_cat: I'll be able to have some free time for contributing on (mostly) daily basis in nearest days so I would be happy to help with all this chore and meta-tasks.

In nearest few days I'll try to make issue with short proposal for things that can be improved (aka roadmap for discussion) and will let you know. I think it might be a good point for me to start.

**Comment by spmasterman** [comment]
@mikegehard - Yeah was just comparing the kotlin exercises with other tracks I've been on - typically there have been files with the skeleton of the solution present, in the Kotlin track that wasn't the case. Its no biggy - just thought I was missing something :D

**Comment by mikegehard** [comment]
Thanks @spmasterman.

@dector is working on a solution so would it be possible to close this issue?

**Comment by dector** [comment]
Actually, there is [PR already](https://github.com/exercism/kotlin/pull/315) (it misses only source file and better commit message). It might be impolite from my side to upload PR that does exactly the same. :)

**Comment by mikegehard** [comment]
@dector I merged in #315 so not sure how that affects #326 

Can you take a look and adjust that PR as necessary?

**Comment by dector** [comment]
@mikegehard I've closed PR, will reopen it for different purpose later.

I guess we need to investigate list of exercises that don't have source files and close this issue when it'll be fixed.

**Comment by dector** [comment]
@spmasterman Thanks for reporting! I'm closing this issue in favor of #310. 

Please, feel free to ping me if you have further questions.
