### ISSUE TITLE
Fix file names for `two-fer`.

### ISSUE THREAD

**Issue by dector** [exercism/kotlin#336]
Because Kotlin style guide forces `CamelCase` for file/class names, we should use `TwoFer`.

Now: [`exercises/two-fer/src/test/kotlin/TwoferTest.kt`](https://github.com/exercism/kotlin/blob/master/exercises/two-fer/src/test/kotlin/TwoferTest.kt#L5).
Should be: `exercises/two-fer/src/test/kotlin/TwoFerTest.kt`.

The main question is if we can just do renaming and it will not break something for somebody.

**Comment by SleeplessByte** [comment]
You can just do the rename. It won't break it for existing users :)
