### ISSUE TITLE
Kotlin track - Forth issue

### ISSUE THREAD

**Issue by anwarsky** [exercism/kotlin#360]
1. No description provided
2. exercism download --exercise=forth --track=kotlin >> Error: failed to parse API error response: invalid character 'o' in literal null (expecting 'u')

**Comment by blueglyph** [comment]
@anwarsky  That'd been reported in #302 already

Since the PR was abandoned, I found a work-around that could allow you to submit the solution, see the comment about 6 months ago, https://github.com/exercism/kotlin/issues/302#issuecomment-515762731

**Comment by eparovyshnaya** [comment]
Closed by [PR 407](https://github.com/exercism/kotlin/pull/407)
