### ISSUE TITLE
Recruiting additional maintainers for Kotlin

### ISSUE THREAD

**Issue by kytrinyx** [exercism/kotlin#406]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by eparovyshnaya** [comment]
Hi! I am an acting maintainer and ready to dedicate requested additional time to V3 activities. 
Also 'll do my best to promote our need.

**Comment by uzilan** [comment]
Hi, I've been trying to assist the maintainers with PRs and reviews and have been acting as a mentor since  the start of v2. I'm willing to help with V3 if needed.

**Comment by mikegehard** [comment]
Hey all...thanks for the ping.

I have been slacking in my maintainer duties for sure and would like to get more involved going forward. :-)

I am not sure I can devote the 2-3 hours / week right now but will step in where I can to help out with the push to v3.

**Comment by dector** [comment]
:wave: Will be able to join more actively in the end of January.

**Comment by 5orry8ro** [comment]
Hey, I just found the site and I've been doing Kotlin, which I really really like. I think the site is a super cool thing and I'd like to pitch in to do some volunteering. I have a background in C#/F#/nodejs/JS/SQL/Kotlin/Powershell/Windows CMD and I've done embedded projects. I don't know how any of this works, so if anyone could shoot me some cliffs, I'd be stoked

**Comment by iHiD** [comment]
@5orry8ro Brilliant. Could you email erik@exercism.io pls (that's @ErikSchierboom) and he'll get you set up :)

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our push to implement the v3 version of this track and v3 has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

New maintainer are always welcome though!
