### ISSUE TITLE
Add example implementations?

### ISSUE THREAD

**Issue by mfoda** [exercism/kotlin#427]
I noticed that many exercises in this track are lacking an example implementation and need some updates to be inline with the new changes mentioned in #423 and #424. Is that something that would be useful to contribute?

**Comment by ErikSchierboom** [comment]
How many exercises are missing an example implementation? If I search for files in the 
exercise's `.meta/src/reference/kotlin` directory I get hits for lots of exercise (see e.g. https://github.com/exercism/kotlin/blob/master/exercises/darts/.meta/src/reference/kotlin/Darts.kt). 

Updating the exercises to the latest version as specified in the canonical data would be a great contribution!

**Comment by mfoda** [comment]
Ah, my bad. I was under the impression that they're added under a `src/example` folder for some reason, but I see the readme notes now. Thanks for the clarification. Will update anything out of date with the canonical data.

**Comment by ErikSchierboom** [comment]
Excellent!
