### ISSUE TITLE
Rename `basics` Concept Exercises to use story/theme

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/kotlin#491]
In the beginning of v3 development, Concept Exercises were named after their Concepts. However, we've later on changed this to have the Concept Exercises be named after their story/theme.

The `basics` Concept Exercise should be updated to use a story/theme-based name and slug.

See https://github.com/exercism/v3-launch/issues/49

**Comment by MisterSadness** [comment]
Seems straightforward enough, I'll like to try this as my first issue
