### ISSUE TITLE
Update Gradle to latest version

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/kotlin#494]
When I open an exercise in IntelliJ, I get a warning message that some Gradle features are no longer supported. It would be nice to not have this warning by upgrading the Gradle version.

**Comment by JonForest** [comment]
FWIW, we also get this in the command line when running the `./gradlew test` command
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

**Comment by incendium** [comment]
This can be closed as #505 has resolved this issue.

**Comment by SleeplessByte** [comment]
Thanks @incendium for the ping.
