### ISSUE TITLE
Need to chage this test case.

### ISSUE THREAD

**Issue by rakibhasan1030** [exercism/kotlin#596]
https://github.com/exercism/kotlin/blob/83020f1e249e826bb56464456974f60d09d9eaad/exercises/practice/two-fer/src/test/kotlin/TwoFerTest.kt#L9C54-L9C54

**Comment by SleeplessByte** [comment]
There is nothing wrong with that particular test. Instead of trying to change the tests, try to change the implementation so that the argument is optional.
