### ISSUE TITLE
Unnecessary semi-colons in Kotlin snippets

### ISSUE THREAD

**Issue by dbikic** [exercism/kotlin#71]
Feel free to close if you think it's unnecessary or it's on purpose, but I found two redundant commas in Kotlin snippets in the TUTORIAL.md file.

The location of the commas are [here](https://github.com/exercism/kotlin/blame/master/exercises/hello-world/TUTORIAL.md#L156) and [here](https://github.com/exercism/kotlin/blame/master/exercises/hello-world/TUTORIAL.md#L554).

:)

**Comment by stkent** [comment]
Good spot! Those symbols are actually called semi-colons, but you're right that they are typically omitted (unless necessary) in idiomatic Kotlin code. If you're up for it, we'd welcome a pull request that removes them both. If not, we're also happy to take care of it :)

**Comment by dbikic** [comment]
Before I filled the issue, I made a commit with the fix, but I don't have access rights to [push](https://scr.infinum.co/dino_bikic/1._dinoDinos-MacBook-Pro_Documentskotlin_zsh_2017-06-23_08-41-05.png) to your repo. Am I doing something wrong?

**Comment by stkent** [comment]
Nope, that's expected! The usual workflow in this case is as follows:

1. create your own [fork](https://help.github.com/articles/fork-a-repo/) of this repository;
1. [define a new remote](https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes) in your local git repository that points to your new fork;
1. push your updated branch to your own fork;
1. open a pull request from your fork into this repository.

Let me know if you run into trouble with any of these steps :)

A tip for the future is that if you're making a small edit such as the one we're discussing here, you can do so using GitHub's web editor, and when you commit it will automatically create that fork for you! That saves you from going through a bunch of the steps listed above!

**Comment by stkent** [comment]
Closed by #90.
